kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storageclass-pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class:  ceph-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
