apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: galera
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  rbd:
    monitors:
      - 192.168.76.10:6789
      - 192.168.76.11:6789
      - 192.168.76.14:6789
    pool: rbd
    image: test-image
    user: admin
    secretRef:
      name: ceph-secret
  persistentVolumeReclaimPolicy: Recycle
