apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv
spec:
  capacity:
    storage: 2048Mi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 192.168.76.10:6789,192.168.76.11:6789,192.168.76.14:6789
    path: /
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
