apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod1-with-secret
spec:
  containers:
  - name: ceph-nginx
    image: nginx:alpine
    volumeMounts:
    - name: ceph-vol1
      mountPath: /usr/share/nginx/html
      readOnly: false
  volumes:
  - name: ceph-vol1
    cephfs:
      monitors:
      - 192.168.76.10:6789,192.168.76.11:6789,192.168.76.14:6789
      user: admin
      secretFile: "/etc/ceph/admin.secre"
      #userSecretName: ceph-secret
      readOnly: false
