apiVersion: v1
kind: Pod
metadata:
  name: cephfs-pod4-with-secret-pvc
spec:
  containers:
  - name: ceph-nginx
    image: nginx:alpine
    volumeMounts:
    - name: ceph-vol1
      mountPath: /usr/share/nginx/html
      readOnly: false
  volumes:
  - name: ceph-vol1
    persistentVolumeClaim:
      claimName: cephfs-claim
