apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: ceph-rbd-test
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.76.10:6789,192.168.76.11:6789,192.168.76.14:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: data
  userId: admin
  userSecretName: ceph-secret
